config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resources :words, only: %i(index)
  resources :categories, only: %i(index show) do
    resources :lessons, only: %i(create)
  end
  resources :activities, only: %i(index show)
  resources :lessons, only: %i(index show update)
  resources :relationships,       only: [:create, :destroy]

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  namespace :admin do
    root "admin#index"
    resources :users, except: %i(show)
    resources :lessons, except: %i(show)
    resources :words, except: %i(show)
    resources :categories
    resources :activities
  end
end

app/models/word.rb
class Word < ApplicationRecord
  has_many :results
  has_many :answers, dependent: :destroy
  belongs_to :category
  paginates_per Settings.perpage

  validates :content, presence: true, uniqueness: true
  validate :must_be_a_answer_correct, on: [:create, :update]

  accepts_nested_attributes_for :answers, reject_if: :all_blank,
    allow_destroy: true

  scope :order_date_desc, ->{order created_at: :desc}
  scope :select_fields, ->{select :id, :content, :category_id}
  scope :alls, ->(user_id){}
  scope :learned, lambda {|user_id|
    where "id in (select word_id from answers where correct='true' and id in
      (select answer_id from results where lesson_id in
        (select id from lessons where user_id = #{user_id})))"}
  scope :unlearned, lambda {|user_id|
    where "id in (select word_id from answers where correct='false' and id in
      (select answer_id from results where lesson_id in
        (select id from lessons where user_id = #{user_id})))"}

  def must_be_a_answer_correct
    unless self.answers.select{|answer| answer.correct}.size == Settings.answer
      errors.add(:one, I18n.t("message.must_a_answer_correct"))
    end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < Admin::BaseController
  before_action :load_word, only: %i(edit update destroy)
  before_action :load_category, only: %i(create update)

  def index
    @q = Word.search params[:q]
    @words = @q.result.select_fields.order_date_desc.page params[:page]
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:success] = t "flash.create_success"
    else
      flash[:danger] = t ".flash.create_fail"
    end
    redirect_to admin_words_path
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t "flash.update_success"
    else
      flash[:danger] = t "flash.update_fail"
    end
    redirect_to admin_words_path
  end

  def destroy
    if @word.destroy
      flash[:success] = t "flash.delete"
    else
      flash[:danger] = t "flash.delete_fail"
    end
    redirect_to admin_words_path
  end

  private

  def load_category
    @categories = Category.all
  end

  def word_params
    params.require(:word).permit :content, :category_id,
      answers_attributes: [:id, :content, :correct, :_destroy]
  end

  def load_word
    @word = Word.includes(:category).find_by id: params[:id]
    return if @word
    flash[:danger] = t "flash.load_word#{params[:id]}"
    redirect_to root_url
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user

  def index
    @words = Word.includes(:category).select_fields.order_date_desc
      .page params[:page]
    @categories = Category.select(:id, :name)
    if !params[:category_id].nil? && params[:category_id].empty?
      @words = Word.send(params[:option], current_user.id).select_fields
        .order_date_desc.page params[:page]
    elsif category = @categories.find_by(id: params[:category_id])
      @words = category.words.send(params[:option], current_user.id)
        .select_fields.order_date_desc.page params[:page]
    else
      @words = Word.includes(:category).select_fields.order_date_desc
        .page params[:page]
    end
  end
end

app/views/admin/words/_answer_fields.html.erb
<p class="fields">
  <span class="input-group-addon">
    <%= f.text_field :content %>
    <%= link_to "#", class: "btn-remove-answer" do %>
    <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  </span>
  <span class="input-group-addon">
   <%= f.label :correct %>
    <%= f.check_box :correct %>

    <%= f.hidden_field :_destroy %>

  </span>
</p>

app/views/admin/words/_word.html.erb
<tr>
  <td><%= word.content %></td>
  <td><%= word.category.name %></td>
  <td><%= word.answers.answer_correct.content %></td>
  <td><%= link_to edit_admin_word_path(word) do %>
    <span class="glyphicon glyphicon-edit"></span>
  <% end %></td>
  <td><%= link_to admin_word_path(word), method: :delete, data: {confirm: t("you_sure")} do %>
    <span class="glyphicon glyphicon-trash"></span>
  <% end %></td>
</tr>

app/views/admin/words/_word_form.html.erb
<%= form_for [:admin, @word] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content, class: "form-control" %>

  <%= f.label :category %>
  <%= f.collection_select :category_id, Category.all, :id, :name , class: "form-control"%>
  <br>

  <%= f.label :answers %>
  <%= f.fields_for :answers do |builder| %>
    <%= render "answer_fields", f: builder %>
  <% end %>
  <p><%= link_to_add_fields (t "add_answer"), f, :answers %></p>
  <div class="col-md-8 col-md-offset-5">
    <%= f.submit t("create"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/words/edit.html.erb
<div class="col-md-9 col-md-offset-3">
  <div class="col-md-12">
    <%= render "word_form" %>
  </div>
<div class="col-md-9 col-md-offset-3">

app/views/admin/words/index.html.erb
<div class="col-md-10 col-md-offset-3">
  <div class="col-md-10">
    <div class="card mb-3">
      <div class="card-header">
        <h1><%= t "all_word" %></h1>
      </div>
      <div class="row">
      <div class="col-md-8 col-md-offset-3">
        <%= search_form_for [:admin, @q] do |f| %>
          <div class="col-md-6"><%= f.text_field :content_cont, class: "form-control", placeholder: t("fillname") %></div>
          <div class="col-md-4"><%= f.submit t("search"), class: "btn btn-primary" %></div>
        <% end %>
      </div>
        <div class="col-md-offset-1">
          <br>
          <%= link_to t(:create_word), new_admin_word_url, class: "btn btn-primary" %>
          <div class="card-body">
            <br>
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable">
                <thead>
                  <tr>
                    <th><%= t "content" %></th>
                    <th><%= t "category" %></th>
                    <th><%= t "meaning" %></th>
                  </tr>
                </thead>
                <tbody>
                  <%= render partial:"admin/words/word", collection: @words %>
                </tbody>
              </table>
            </div>
            <div class="text-center">
              <%= paginate @words %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/words/new.html.erb
<div class="col-md-12">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1><%=t ".create_word" %></h1>
      <%= render "word_form" %>
    </div>
  </div>
</div>