config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resources :words, only: %i(index)
  resources :categories, only: %i(index show) do
    resources :lessons, only: %i(create)
  end
  resources :activities, only: %i(index show)
  resources :lessons, only: %i(index show update)
  resources :relationships,       only: [:create, :destroy]

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  namespace :admin do
    root "admin#index"
    resources :users, except: %i(show)
    resources :lessons, except: %i(show)
    resources :words, except: %i(show)
    resources :categories
    resources :activities
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons
  has_many :words, dependent: :restrict_with_exception

  validates :name, presence: true, length: {maximum: Settings.category_name}
  validates :duration, presence: true
  paginates_per Settings.cate_perpage

  scope :order_date_desc, ->{order created_at: :desc}
  scope :select_fields, ->{select :id, :name}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :load_category, only: %i(edit update destroy)

  def index
     @q = Category.search params[:q]
    @categories = @q.result.select_fields.order_date_desc.page params[:page]
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "flash.create_success"
    else
      flash[:danger] = t "flash.create_fail"
    end
    redirect_to admin_categories_path
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "flash.update_success"
    else
      flash[:success] = t "flash.update_fail"
    end
    redirect_to admin_categories_path
  end

  def destroy
    begin
      @category.destroy
      flash[:success] = t "delete_cate"
    rescue ActiveRecord::DeleteRestrictionError => e
      @category.errors.add(:exception, e)
      flash[:error] = "#{e}"
    ensure
      redirect_to admin_categories_path
    end
  end

  private

  def category_params
    params.require(:category).permit :name, :duration
  end

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
    flash[:danger] = t "flash.load_category#{params[:id]}"
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :load_category, only: :show

  def index
    @q = Category.search params[:q]
    @categories = @q.result.select_fields.order_date_desc.page params[:page]
  end

  def show
    @lessons = @category.lessons.select_fields.order_date_desc.page params[:page]
  end

  private

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
    flash[:danger] = t "flash.load_category#{params[:id]}"
    redirect_to root_path
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= link_to category.name, category_path(category) %></td>
  <td><%= link_to edit_admin_category_path(category) do %>
    <span class="glyphicon glyphicon-edit"></span>
  <% end %></td>
  <td><%= link_to admin_category_path(category), method: :delete, data: {confirm: t("you_sure")} do %>
    <span class="glyphicon glyphicon-trash"></span>
  <% end %></td>
</tr>

app/views/admin/categories/_category_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %></br>
  <%= f.label :duration %>
  <%= f.text_field :duration, class: "form-control" %></br>
  <%= f.submit t("submit"), class: "btn btn-primary" %>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="col-md-9 col-md-offset-3">
  <div class="col-md-12">
    <h1><%= t "edit" %></h1>
    <div class="card-content">
      <%= render "category_form" %>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="col-md-9 col-md-offset-3">
  <div class="col-md-12">
    <h1><%= t"category" %></h1>
    <div class="row">
      <div class="col-md-8 col-md-offset-3">
        <%= search_form_for @q do |f| %>
          <div class="col-md-6"><%= f.text_field :name_cont, class: "form-control", placeholder: t("fillname") %></div>
          <div class="col-md-4"><%= f.submit t("search"), class: "btn btn-primary" %></div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <%= link_to t("create_category"), new_admin_category_path, class: "btn btn-info"%>
      <br/><br/>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th><%= t ".name" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "category", collection: @categories %>
          </tbody>
        </table>
        <%= paginate @categories %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="col-md-12">
  <div class="row">
    <div class="col-md-6 col-md-offset-5">
      <h2><%= t "submit_create"%></h2>
      <%= render "category_form" %>
    </div>
  </div>
</div>

app/views/admin/categories/show.html.erb
<div class="col-md-9 col-md-offset-3">
  <div class="col-md-12">
    <h2><%= @category.name %></h2>
    <%= link_to t("back"), admin_categories_path %>
    <%= link_to t("edit"), edit_admin_category_path %>
    <%= link_to t("delete"), admin_category_path, method: :delete, data: {confirm: t "confirm"} %>
  </div>
</div>