config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resources :words, only: %i(index)
  resources :categories, only: %i(index show) do
    resources :lessons, only: %i(create)
  end
  resources :activities, only: %i(index show)
  resources :lessons, only: %i(index show update)
  resources :relationships,       only: [:create, :destroy]

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  namespace :admin do
    root "admin#index"
    resources :users, except: %i(show)
    resources :lessons, except: %i(show)
    resources :words, except: %i(show)
    resources :categories
    resources :activities
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :lessons
  has_many :activities
  has_many :active_relationships, class_name:  Relationship.name,
                                   foreign_key: :follower_id,
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  Relationship.name,
                                   foreign_key: :followed_id,
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  paginates_per Settings.perpage

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
    length: {maximum: Settings.user.email.maximum_length},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true,
    length: {minimum: Settings.user.password.minimum_length}, allow_nil: true

  scope :order_date_desc, ->{order created_at: :desc}
  scope :select_fields, ->{select :id, :email}

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :load_user, only: %i(destroy)

  def index
    @q = User.search params[:q]
    @users = @q.result.select_fields.order_date_desc.page params[:page]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "flash.create_success"
    else
      flash[:danger] = t "flash.create_fail"
    end
    redirect_to admin_users_path
  end

  def destroy
    if @user.destroy
      flash[:success] = t "flash.delete"
    else
      flash[:danger] = t "flash.delete_fail"
    end
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t "flash.load_user#{params[:id]}"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :load_user, only: %i(show following followers)

  def index
    @users = User.select_fields.order_date_desc.page params[:page]
  end

  def show
    @unfollow_user = current_user.active_relationships
      .find_by followed_id: @user.id
    @follow_user = current_user.active_relationships.build
    @lessons = User.find(params[:id]).lessons.select_fields.order_date_desc
      .page params[:page]
    @activities = current_user.activities.order_date_desc
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.page params[:page]
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.page params[:page]
    render 'show_follow'
  end

  private

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t "flash.load_user#{params[:id]}"
    redirect_to root_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size: Settings.gravatar})
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end

  def current_user? user
    user == current_user
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit t("submit"), class: "btn btn-primary" %>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
  <td><%= link_to user.email, user_path(user) %></td>
  <td><%= link_to admin_user_path(user), method: :delete,
    data: {confirm: t("you_sure")} do %>
    <span class="glyphicon glyphicon-trash"></span>
  <% end %></td>
</tr>

app/views/admin/users/index.html.erb
<div class="col-md-8 col-md-offset-4">
  <div class="row">
    </br>
    <%= link_to t("create_user"), new_admin_user_path, class: "btn btn-info"%>
    <br/><br/>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= t ".email" %></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "user", collection: @users %>
      </tbody>
    </table>
    <%= paginate @users %>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="col-md-12">
  <div class="row">
    <h1><%= t "create_user" %></h1>
    <div class="col-md-6 col-md-offset-3">
      <%= render "form" %>
    </div>
  </div>
</div>